### ISSUE TITLE
No more free Heroku Dyno hour

### ISSUE THREAD

**Issue by edxu96** [pasty-dev/cmdict#111]
https://blog.heroku.com/next-chapter#focus-on-mission-critical

**Comment by edxu96** [comment]
I don't like Heroku because of [its leak of GitHub tokens](https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/). Also, I cannot add any credit card in order for more free hours. @zequnyu Are you familiar with other service that can run a Python script? The script is used for [the automatic reply in Telegram](https://github.com/pasty-dev/cmdict#quick-start).

**Comment by zequnyu** [comment]
You could probably explore options in AWS.
